config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence:true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def Home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email])

    if user and user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user
    else
      render 'new'
    end
  end
  def destroy
    reset_session
    session[:user_id] = nil
    redirect_to login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id:params[:id])
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      render 'new'
    end
  end

private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user = User.find_by(id: session[:user_id])
  end
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<%= link_to "Home", root_url %>
<% if logged_in? %>
  <%= link_to "My Account", current_user%>
  <%= link_to "Log Out", logout_url, method: :delete%>
<% else %>
  <%= link_to "Login", login_url %>
  <%= link_to "Register", new_user_url%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/header.html.erb'%>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h2>Home</h2>

app/views/users/new.html.erb
<%= form_with model:@user, local:true do |f|%>
  <%= f.label           :email%>
  <%= f.email_field     :email%>
  <%= f.label           :password%>
  <%= f.password_field  :password%>
  <%= f.label           :password_confirmation%>
  <%= f.password_field  :password_confirmation%>
  <%= f.submit "Register"%>
<% end %>

app/views/users/show.html.erb
<br />
<% if @user %>
  Account with email: <b><%= @user.email%></b>
<% else %>
  User does not exist.
<% end %>